export { default as RootAppMaker } from "./root-app"
export { default as VantButtonMaker } from "./vant-button"
export { default as InputInspector } from "./input-inspector/"
export { default as AddMaker } from "./add/index"
export { default as ConstAMaker } from "./const-a/index"
export { default as ConstBMaker } from "./const-b/index"
export { default as GetEventParamMaker } from "./getEventParam/index"